name: Test GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v4

    - name:  Paso 1
      run: echo "Workflow detecto un push en la rama main"

    - name: Mostrar fecha y hora
      run: date

    - name: Verificar versi칩n de Node
      run: node -v || echo "Node no est치 instalado en este runner"

    - name: Verificar versi칩n de Python
      run: python3 --version || echo "Python no este instalado"
